services:
  app:
    extends: 
      file: docker-compose.yml
      service: app
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'sleep 3 && npm run dev' 
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - "./app:/app"
    depends_on:
      - db
  caddy:
    image: caddy:2.6
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
  db:
    image: postgres:16.2
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs: 
          size: 134217728 # 128*2^20 bytes = 128Mb


volumes:
  caddy_data:
  caddy_config:
  # pgdata:
