services:
  app:
    extends: 
      file: docker-compose.yml
      service: app
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - 8080:8080
    volumes:
      - "./app:/app"
  caddy:
    image: caddy:2.6
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:

