---
version: "3"

services:
  app:
    image: ays4/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    command: bash -c 'sleep 3 && make test'
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - db
  
  db:
    image: postgres:16.2
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
